version: '3.8'

services:
  # 前端服务
  stock-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-frontend:latest
    container_name: stock-frontend
    restart: always
    ports:
      - "9009:9009"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://192.168.1.100:9099
    network_mode: "bridge" 