version: '3'

services:
  stock-frontend:
    image: nginx:alpine
    container_name: stock-frontend
    restart: always
    ports:
      - "9009:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx-synology.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Asia/Shanghai
    # 移除命令，不再尝试创建文件
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 