version: '3.8'

services:
  frontend:
    container_name: stock-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9009:80"
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../logs/frontend:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
      - BACKEND_HOST=${BACKEND_HOST:-stock-backend}
      - BACKEND_PORT=${BACKEND_PORT:-9099}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - frontend_network
      - stock-backend_stock-network
    mem_limit: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  frontend_network:
    driver: bridge
  stock-backend_stock-network:
    external: true 