version: '3.8'

services:
  stock-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-frontend:latest
    container_name: stock-frontend
    restart: unless-stopped
    ports:
      - "9009:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx-synology.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - stock-network
      - stock-backend_stock-network

networks:
  stock-network:
    driver: bridge
  stock-backend_stock-network:
    external: true 