version: '3.8'

services:
  # 后端服务
  stock-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: stock-backend:latest
    container_name: stock-backend
    restart: unless-stopped
    ports:
      - "9099:9099"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
      - DB_HOST=mysql-container
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Zxc000123
      - DB_NAME=stock
      - DB_CHARSET=utf8mb4
      - DB_CONNECT_RETRY=5
      - DB_CONNECT_RETRY_DELAY=3
    networks:
      - Stock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    mem_limit: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 前端服务
  stock-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: stock-frontend:latest
    container_name: stock-frontend
    restart: unless-stopped
    ports:
      - "9009:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/frontend:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
      - BACKEND_HOST=stock-backend
      - BACKEND_PORT=9099
      - NODE_ENV=production
    depends_on:
      - stock-backend
    networks:
      - Stock
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    mem_limit: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  Stock:
    external: true 