version: '3.8'

services:
  # 后端服务
  stock-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-backend:latest
    container_name: stock-backend
    restart: unless-stopped
    ports:
      - "9099:9099"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
      - DB_CONNECT_RETRY=5
      - DB_CONNECT_TIMEOUT=10
      - DB_CONNECT_RETRY_DELAY=3
    # 使用主机网络模式，直接使用宿主机网络，解决网络隔离问题
    network_mode: "host"
    # 添加健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # 只保留内存限制，移除CPU限制
    mem_limit: 1G

# 不再需要volumes和networks配置 